module.exports = {
  preset: 'ts-jest',
  setupFiles: ['<rootDir>/src/setupTests.ts'],
  testEnvironment: 'jest-environment-jsdom',
  transform: {
    '^.+\\.(js|jsx|ts|tsx)$': 'babel-jest',
    '^.+\\.(css|scss)$': 'jest-transform-stub',
  },
  setupFilesAfterEnv: ['./jest.setup.js'], 
  transformIgnorePatterns: [
   'node_modules/(?!(react-leaflet|leaflet)/)', 
    '/node_modules/',
    '^.+\\.css$',
  ],
  moduleNameMapper: {
    '\\.(gif|ttf|eot|svg|png)$': '<rootDir>/test/__mocks__/fileMock.js',
    '\\.scss$': '<rootDir>/test/__mocks__/styleMock.js',
    '\\.(css|less)$': 'identity-obj-proxy',
    '^react-native$': 'react-native-web',
    '^react-leaflet$': '<rootDir>/node_modules/react-leaflet/lib/index.js',
    "^components/(.*)$": "<rootDir>/src/components/$1",
    "^assets/(.*)$": "<rootDir>/src/assets/$1",
    "^utils/(.*)$": "<rootDir>/src/utils/$1",
    "^pages/(.*)$": "<rootDir>/src/pages/$1",
    "^context/(.*)$": "<rootDir>/src/context/$1",
    "^Theme$": "<rootDir>/src/context/ThemeContext",
    '^routes$': '<rootDir>/src/routes',
    '^apis/(.*)$': '<rootDir>/src/apis/$1',
    '^interfaces$': '<rootDir>/src/interfaces/$1',
    '^redux/(.*)$': '<rootDir>/src/redux/$1',
    '^router/(.*)$': '<rootDir>/src/router/$1',
    '^types$': '<rootDir>/src/types/$1',
    '^enum/(.*)$': '<rootDir>/src/enum/$1',
    '^constants/(.*)$': '<rootDir>/src/constants/$1',
    '^src/(.*)$': '<rootDir>/src/$1',
  },
};
